# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: example-agent-optimizer
metadata:
    template: example-agent-optimizer@1.0.0
services:
    support-agent:
        project: ./src/support-agent
        host: azure.ai.agent
        language: python
        config:
            container:
                resources:
                    cpu: "0.5"
                    memory: 1Gi
            deployments:
                - model:
                    format: OpenAI
                    name: gpt-4o
                    version: "2024-11-20"
                  name: gpt-4o
                  sku:
                    capacity: 50
                    name: GlobalStandard
